# Generated by Django 5.1.7 on 2025-03-12 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PA', 'Pasaporte'), ('CE', 'Cédula de Extranjería')], max_length=2)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('numero_celular', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vacuna', models.CharField(choices=[('COVID-19', 'Vacuna contra el COVID-19'), ('Influenza', 'Vacuna contra la Influenza'), ('Tétanos', 'Vacuna contra el Tétanos')], max_length=20)),
                ('fecha_aplicacion', models.DateField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='clientes.persona')),
            ],
        ),
    ]
